### ISSUE TITLE
Long & Lat or entering address into marker issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#25]
Marker does not go to correct position on map, I did try switching the cords around but that didnt help, here's a screencast:

http://youtu.be/trZqltXB87A?hd=1

**Comment by selul** [comment]
@contactashish13 can you check what could be the issue here?

**Comment by contactashish13** [comment]
pushed in the fix

**Comment by selul** [comment]
@UVLabs can you help me test to see if is working fine now ?

**Comment by UVLabs** [comment]
@selul sure

**Comment by UVLabs** [comment]
@selul I downloaded the development copy but the issue still exists, it did get better, but not exactly like what I'm getting from maps.google.com maybe you could test with your area

**Comment by selul** [comment]
@contactashish13 can you please check ? Please try to any location, just copy paste the lat/long and see if is the exact point as in the maps.google.com

**Comment by contactashish13** [comment]
@selul it works. I think the problem is one has to right click on google maps and click "whats here?" to get the exact lat/lon. copy pasting from the url gives a slightly different value because it also involves panning the map.

I'm plotting nelson's column

![image](https://cloud.githubusercontent.com/assets/12953439/16920098/f1f12af2-4d29-11e6-90ef-d7594539e26b.png)

![image](https://cloud.githubusercontent.com/assets/12953439/16920148/24302752-4d2a-11e6-899f-7483fb56f3e6.png)

**Comment by selul** [comment]
@contactashish13 ok, this can be closed then
