### ISSUE TITLE
Supprot Issues: Export not working & directions

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/intergeo-maps#48]
https://secure.helpscout.net/conversation/278858997/119322/ and https://secure.helpscout.net/conversation/277721544/0/

- Marker export feature isn't working, same goes for import.
- The user in one thread is having issues when adding the map. Directions aren't appearing on the front-end.

@selul @contactashish13 

Edit: This issue will cover a few more issues:

1. When multiple maps are created in the library and the last map is edited, its options are incorrectly saved/shown.
To reproduce:
- Delete all maps
- Create a map with markers imported from a csv (check the Import from Computer checkbox)
- Create a map with driving directions (do not Import from Computer checkbox)
- In the library, edit the second map. The Import from Computer checkbox will be checked.

2. When the API key does not support a given API, show an error

3. Some features are supported only in pro. When lite is activated, the accordions corresponding to them should not be shown. e.g. drawing tools.

4. Blue marker icon is ignored when adding markers and always defaults to red marker.

**Comment by suyogyashukla** [comment]
+1

**Comment by contactashish13** [comment]
@selul I dont have access to helscount. I tried to use forgot password but never received the email. Can you please mention what the issues are?

**Comment by selul** [comment]
@contactashish13 @suyogyashukla can you help ash replicate the issue, maybe provide the csv files you tested

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/intergeo-maps/pull/78 and https://github.com/Codeinwp/intergeo-maps-pro/pull/38

@HardeepAsrani I was not able to reproduce the error with directions.

**Comment by contactashish13** [comment]
@rodica-andronache have fixed all issues I could find. 

If the API does not support driving directions, it does throw an error while editing the map. I've added the error code from google as well to make it a little clearer. 

On the front end, I'm showing this same kind of alert only if the user is logged in. I'm assuming that the user who adds the shortcode will test it first. If the user creates the shortcode and does not test it, end users will not know why it is not working; they can still check the console for errors though. This must be highlighted in the user docs because the JS console gives the most descriptive error for any scenario.

I think this plugin needs a thorough testing so that more issues, if they exist, can be discovered and solved in one go :)

**Comment by rodica-andronache** [comment]
@contactashish13 you are right, I am planning to test the plugin a bit more, but for sure, if by then you find other problems you can add them on git 👍
